### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by jingsam** [trixon/mapton#40]
Great work! I have download v1.1.2. How can I get the program to run?

**Comment by trixon** [comment]
@jingsam 
Well, that depends on your environment.
Mapton requires Java 8 with JavaFx.
If that's not your default jre you can edit the file mapton/etc/mapton.conf.
Set jdkhome="/path/to/jdk" so it points to your jre, or give it as an argument when starting
mapton --jdkhome <path>
