### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by leowhss** [trixon/mapton#52]
Hello,

On compiling Mapton v2.2.0 from source, missing the following 11.0.8 versions from https://dl.bintray.com/trixon/maven:

se.trixon.almond:almond-nbp-core:jar:11.0.8-SNAPSHOT
se.trixon.almond:almond-util:jar:11.0.8-SNAPSHOT

As of today, I can only see up till v11.0.7 for the above.

Thanks for open sourcing Mapton!

Thanks!

Sean

**Comment by trixon** [comment]
Hello @leowhss,
I'll have to sort things out regarding the bintray shutdown, but until then, clone and build
https://github.com/trixon/almond3/commit/e4109a6d5b0cb3c24b5f262e8e0f1a1627a67f98

**Comment by ghasem110** [comment]
hi 
when i was to build mapton in netbeans 12.3 and jdk 16, this error occured in mapton-base module:
Failed to execute goal org.apache.netbeans.utilities:nbm-maven-plugin:4.6:manifest (default-manifest) on project mapton-base: Uncategorized problems with NetBeans dependency verification (maybe MNBMODULE-102 or wrong maven dependency metadata). Supposedly external classes are used in the project's binaries but the classes are not found on classpath. Class usages: [java.lang.Module] -> [Help 1]

**Comment by trixon** [comment]
@leowhss I added an instruction for building until the missing artifact is published. https://github.com/trixon/mapton#building-mapton
